### ISSUE TITLE
QA code to be released?

### ISSUE THREAD

**Issue by svenwoldt** [miyyer/dan#2]
Hey there,

I was wondering you mention in your repo that code for question-answering would be showcased soon, are you still planning to do so with DAN?

I would like to integrate DAN into NAO (Aldebarans humanoid robot) for a research project on robot interactions and was wondering if I could collaborate with you on DAN this way.

**Comment by miyyer** [comment]
hey, sorry forgot about this. we actually released a QA version of the DAN as part of our quiz bowl system code here: https://github.com/Pinafore/qb/blob/master/guesser/dan.py

thanks for bringing this up! feel free to email me if you have specific questions about how you can use the code.
